baseURL = "https://podcast.dvor.me/"
languageCode = "ru"
title = "День за днём"

publishDir = "docs"

[params]
  description = "Истории из жизни в Нидерландах, а также абстрактные (и не очень) рассуждения на множество тем."
  media_prefix = "https://media.blubrry.com/dvor/podcastdvor.ams3.cdn.digitaloceanspaces.com/"

  author = "dvor"

  email = "d@dvor.me"
  telegram = "d_vor"
  facebook = "dmytro.vorobiov.31"
  vkontakte = "d_vor"
  instagram = "__dvor"

  rss_url = "https://podcast.dvor.me/posts/index.xml"
  itunes_url = "https://itunes.apple.com/nl/podcast/%D0%B4%D0%B5%D0%BD%D1%8C-%D0%B7%D0%B0-%D0%B4%D0%BD%D1%91%D0%BC/id1457128650"
  spotify_url = "https://open.spotify.com/show/2CeVRtHtyW6TI6Ams7pEE5?si=FGWBe1gOQB2zkDQTfpH01A"
  google_play_url = "https://playmusic.app.goo.gl/?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&apn=com.google.android.music&link=https://play.google.com/music/m/Iguhwhngzhit5muhbknipl7ionq?t%3D%25D0%2594%25D0%25B5%25D0%25BD%25D1%258C_%25D0%25B7%25D0%25B0_%25D0%25B4%25D0%25BD%25D1%2591%25D0%25BC%26pcampaignid%3DMKT-na-all-co-pr-mu-pod-16"

  [params.feed]
    copyright = "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License"

    itunes_subtitle = "Истории из жизни в Нидерландах."
    itunes_author = "dvor"
    itunes_owner_name = "dvor"
    itunes_owner_email = "d@dvor.me"
    itunes_summary = "Истории из жизни в Нидерландах, а также абстрактные (и не очень) рассуждения на множество тем."
    itunes_image = "https://podcast.dvor.me/images/podcast-cover-large.jpg"
    itunes_top_category = "Society & Culture"
    itunes_first_sub_category = "Personal Journals"
    explicit = "no"
